version: '3'

services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html
        links:
            - 'mariadb'
        environment:
            BASE_URL: "http://localhost/"
            DB_CONTAINER_NAME: "mariadb"
            DB_CONTAINER_PORT: 3306
        env_file:
            - database.env

    mariadb:
        # https://mariadb.org/
        # https://hub.docker.com/_/mariadb
        image: mariadb:10.5.4
        command:
            mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - 3306:3306
        volumes:
            - mariadb:/var/lib/mysql
            - ./db-dumps:/docker-entrypoint-initdb.d
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
        env_file:
            - database.env

    phpmyadmin:
        # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        depends_on:
            - mariadb

volumes:
    mariadb:
