version: '3'

services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html
        links:
            - 'mariadb'

    mariadb:
        # https://mariadb.org/
        # https://hub.docker.com/_/mariadb
        image: mariadb:10.5.4
        volumes:
            - mariadb:/var/lib/mysql
            - ./db-dumps:/docker-entrypoint-initdb.d
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'hash-admin'
            MYSQL_PASSWORD: 'secret-password'
            MYSQL_DATABASE: 'hash_magazine'

    phpmyadmin:
        # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        depends_on:
            - mariadb

volumes:
    mariadb:
